# LINK TO GITHUB QUESTION YOU WANT TO SCRAPE
question_link = """
https://leetcode.com/problems/reverse-integer/description/
"""


output_folder = ""  # Leave blank to save to root
templates_folder = "templates"